//Minting Scripts

//0-25
{
  "721": {
    "<policy>": {
        "TURT001": {
          "name": "Lil Turt #001",
          "image": "ipfs://QmUy2ypzfUPAcmZxXDMRQnFYQNEgC2g7i2VA3obpzk2tgy",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "none ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Sign ",
          "weapons": "Staff Left (rare)",
          "wings": "Dark Angel Wings (super super rare)"
        },
        "TURT002": {
          "name": "Lil Turt #002",
          "image": "ipfs://QmPT36zNe8Spfc95qQRrAAwxnw5h4ASLztQUpDpUc8BSwf",
          "background": "Purple ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "Angel Wings (super super rare)"
        },
        "TURT003": {
          "name": "Lil Turt #003",
          "image": "ipfs://QmS3SUoevBEm9Ga1d5uYxY3JMKWg67izuMsH2fZTbd9FKY",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT004": {
          "name": "Lil Turt #004",
          "image": "ipfs://QmfL4mLZ37PXX6xEvoZaJeLq8efKHq5uzphfhzsWBPFKiQ",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT005": {
          "name": "Lil Turt #005",
          "image": "ipfs://QmeH6SvYL7ZMBy7GsnkWPLrYz795H5sLUXqmV6BCmWSVvt",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Winter Hat ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "Dark Angel Wings (super super rare)"
        },
        "TURT006": {
          "name": "Lil Turt #006",
          "image": "ipfs://Qma8SqmL8453wfCi21j3FLHiVYC7CBJQpdrM7PAF91Ax95",
          "background": "Blue ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Steel Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "Angel Wings (super super rare)"
        },
        "TURT007": {
          "name": "Lil Turt #007",
          "image": "ipfs://Qmb8sB46Xjxrsyb9RoBawB8ofwPm53twJn4qdWcoT2PuGv",
          "background": "Pink ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT008": {
          "name": "Lil Turt #008",
          "image": "ipfs://QmdM65d6VfvMgMbkQcrGD4KCPPj9CgBBGdUSLnRBYmsN3Q",
          "background": "Purple ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "none ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT009": {
          "name": "Lil Turt #009",
          "image": "ipfs://QmcKbWcphUS7f6djrP8RjiWw5d4eb57FjBfoNM9EF728d2",
          "background": "Pink ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Steel Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT010": {
          "name": "Lil Turt #010",
          "image": "ipfs://QmabgDfbieDHYfnCJeeVVh6f1y8C9xeQ72k8nMtmdhCPHE",
          "background": "Blue ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "White Hair ",
          "shell": "Base Shell ",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT011": {
          "name": "Lil Turt #011",
          "image": "ipfs://QmTwMd4xHUaoxDiyzwC7PRdjrX1uVv57Y1wgJkMnC9bpdu",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT012": {
          "name": "Lil Turt #012",
          "image": "ipfs://QmdB5J9vM7dkyWHzC6s4aDFTT9fMydPwktTBjQsDnN2p3E",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "none ",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT013": {
          "name": "Lil Turt #013",
          "image": "ipfs://QmRrcyPm2P6pSYD4BbHns7srNS8S4GfkgKEiNg6FG9E3RB",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT014": {
          "name": "Lil Turt #014",
          "image": "ipfs://QmTAAASwCj19M3dZXxZ4gmYTnFfT1uQ8q3X9SXyaAt9zm2",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT015": {
          "name": "Lil Turt #015",
          "image": "ipfs://QmWz634EQXHuyJQaRDuVfKrKponoKbuH8XD3gPRgN1sLzr",
          "background": "Tan ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT016": {
          "name": "Lil Turt #016",
          "image": "ipfs://QmWVRyVR7nQfjT1UWkUbiYjmobLecrVU4iyDaLRd1PiEuF",
          "background": "Purple ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT017": {
          "name": "Lil Turt #017",
          "image": "ipfs://QmNdN396XB3mEJhawHewkurq6dJdHy6ZGb13Nj8qzPfQ6R",
          "background": "Purple ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Steel Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "Rainbow Wings (super super rare)"
        },
        "TURT018": {
          "name": "Lil Turt #018",
          "image": "ipfs://QmUP2SZAw1y9JiZhD1PbZBtyEvd1DCKvWqL8iB7TEGxT9u",
          "background": "Purple ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT019": {
          "name": "Lil Turt #019",
          "image": "ipfs://QmaDwsNxNVuDr9mto9pUYFX9QoaMpkSi6i9Y9RbBoyTUA8",
          "background": "Purple ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "Double Staff (rare)",
          "wings": "none "
        },
        "TURT020": {
          "name": "Lil Turt #020",
          "image": "ipfs://QmUarcxdiY9DQtGSn13UzuTG4UySLWw3YN2B91weoE9CQn",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "none ",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT021": {
          "name": "Lil Turt #021",
          "image": "ipfs://QmaWe2DGQmfxQQqrCoYKHC5HWGWdT23Hqq7X7Hn1A78Kp6",
          "background": "Pink ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Steel Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "Rainbow Wings (super super rare)"
        },
        "TURT022": {
          "name": "Lil Turt #022",
          "image": "ipfs://QmdgkiwL7EiaX8cjEtm4UJYxAUCFgPCL5DeMBq5GWrJRXp",
          "background": "Pink ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "Staff Left (rare)",
          "wings": "none "
        },
        "TURT023": {
          "name": "Lil Turt #023",
          "image": "ipfs://QmcnArTZpQx9a7iuokUJA1SN2ZEbCcXUj7cFQVmdiLqDPi",
          "background": "Purple ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT024": {
          "name": "Lil Turt #024",
          "image": "ipfs://QmSii5wD7h4DiJBDoMePZ9z8tBnFPXw7UKdPxTftDEdtmv",
          "background": "Purple ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        },
        "TURT025": {
          "name": "Lil Turt #025",
          "image": "ipfs://QmWLjsKMrGWEihj38SwRLZVumpPBSV5b1sJxuFD6WWrzd2",
          "background": "Pink ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
        }
    }
  }
}

//26-50

{
  "721": {
    "<policy>": {
        "TURT026": {
          "name": "Lil Turt #026",
          "image": "ipfs://QmT27YNRjmLT54jXZWRKiHBeF4PhQN4hRK8Pq7AQnZXVBo",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT027": {
          "name": "Lil Turt #027",
          "image": "ipfs://QmcLVC2LSmjrXK4oQb2nMPG5PdFDhihuN3bA5nbxmPssF4",
          "background": "Pink ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Base Shell ",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT028": {
          "name": "Lil Turt #028",
          "image": "ipfs://QmX19rXNzF8TkMLuf2c9uabCA3CuBT5nyvNiDhkkJYCJJe",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Gold Shell (super rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "Staff Left (rare)",
          "wings": "Rainbow Wings (super super rare)"
      },
        "TURT029": {
          "name": "Lil Turt #029",
          "image": "ipfs://QmTnsNjDQDKVu7Xr8GW5ZuTum8kYBs2YfSb7SnLgNeutxe",
          "background": "Pink ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "Winter Hat ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Flowers ",
          "weapons": "Staff Right (rare)",
          "wings": "none "
      },
        "TURT030": {
          "name": "Lil Turt #030",
          "image": "ipfs://QmY553y2oHpkNjFcJQHjjr4cEdbsfqW493fLK8FkA6SmnM",
          "background": "Pink ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "Winter Hat ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "Staff Left (rare)",
          "wings": "none "
      },
        "TURT031": {
          "name": "Lil Turt #031",
          "image": "ipfs://QmbnTeNV8NV83b9fsR8DG5dFWtpURHFRg9uXEhKNLbPgGe",
          "background": "Purple ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Winter Hat ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT032": {
          "name": "Lil Turt #032",
          "image": "ipfs://QmSKtnrkyXsztVquQRdFbhS4dDyhJZJ1KjnCoAojC1BgGn",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Base Shell ",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT033": {
          "name": "Lil Turt #033",
          "image": "ipfs://QmeN3PWsbcTNbC85P9cER85eQ7YNghzA8JcHnsZ3Pmth6x",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT034": {
          "name": "Lil Turt #034",
          "image": "ipfs://QmUiYpcET8KZr4D7d2JJ8umNUHwvcsqU1pTfBTabbNqB87",
          "background": "Purple ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Gold Shell (super rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT035": {
          "name": "Lil Turt #035",
          "image": "ipfs://QmX2h7dM595mkokD25JjQTeWbVnNnCtXmzUYKze22RzsUB",
          "background": "Purple ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT036": {
          "name": "Lil Turt #036",
          "image": "ipfs://QmVXBgkNPczMTjcKPCWhwb9FTA458yyMJoPSWe2g6pjKCi",
          "background": "Tan ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT037": {
          "name": "Lil Turt #037",
          "image": "ipfs://QmPGtod4B8skkVLKPwgAAZttdGz2R8f7qBjgr3JbNoZqDV",
          "background": "Tan ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Steel Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT038": {
          "name": "Lil Turt #038",
          "image": "ipfs://Qmexu9pwZqHq1PHTyNjyA9yFRGgVnRwVakAvMMeu65qDSJ",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT039": {
          "name": "Lil Turt #039",
          "image": "ipfs://QmaHTNRNJ85a6CcXfc2vXkkgJ8JXADnmdBYDJiYvFgsB8W",
          "background": "Tan ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT040": {
          "name": "Lil Turt #040",
          "image": "ipfs://QmYzefv2yaSYuPoeM1s9VmNLCwN46ZcTpT7sCrPkUiTu6R",
          "background": "Pink ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Steel Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT041": {
          "name": "Lil Turt #041",
          "image": "ipfs://QmeYEmhnM9eoyANfDzPTzTUM2x6YPzhdG5wAW3KBBTjfVR",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Steel Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "Double Staff (rare)",
          "wings": "none "
      },
        "TURT042": {
          "name": "Lil Turt #042",
          "image": "ipfs://QmQ3epDepttFezrhFXZeNAJSnRHMXmXTrddh7CTDhWEeJN",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "White Hair ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT043": {
          "name": "Lil Turt #043",
          "image": "ipfs://QmQwijNhfr1tP1TYzzi2DgvFPm8wM38FLPwuNVz72MLxqV",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "Staff Right (rare)",
          "wings": "none "
      },
        "TURT044": {
          "name": "Lil Turt #044",
          "image": "ipfs://QmPsfEUH2vsXPemHzLUNga5LXmz7nRTjbP9GHi2DcYf4YX",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Steel Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT045": {
          "name": "Lil Turt #045",
          "image": "ipfs://QmdjghV79JgcWt7gXmFR9kqD2ou1rF9kCVQ6xQ8a1DU5Pp",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT046": {
          "name": "Lil Turt #046",
          "image": "ipfs://QmYMgGk3btEPJvvvcYcPLnoTYqd8TwB2jEGKJbKXXididF",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "Double Staff (rare)",
          "wings": "none "
      },
        "TURT047": {
          "name": "Lil Turt #047",
          "image": "ipfs://QmW2hzyVuvRJC8s35aYcSqSoj2KpoP5g2TsZSbMUJL2fAX",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "Rainbow Wings (super super rare)"
      },
        "TURT048": {
          "name": "Lil Turt #048",
          "image": "ipfs://Qme8Eyze4twGeFbthxZMcsLddC3EuWXnwQNU6aaorBSLDT",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Gold Shell (super rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT049": {
          "name": "Lil Turt #049",
          "image": "ipfs://Qmd9v4XZ1psaSz3iqANEo5sQPkiV3WHu6T1CkDUXXDsBPK",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT050": {
          "name": "Lil Turt #050",
          "image": "ipfs://QmeWRWTHdNMt3B9tXbFfzJh78AS69UAFBQS9qwB14toQED",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "Double Staff (rare)",
          "wings": "none "
      }
    }
  }
}

//51-75

{
  "721": {
    "<policy>": {
        "TURT051": {
          "name": "Lil Turt #051",
          "image": "ipfs://QmNWRG2naBKzVxtgcHbjzdxwwYZ5qHSJmAY3Ak6C4EaBNn",
          "background": "Tan ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Steel Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT052": {
          "name": "Lil Turt #052",
          "image": "ipfs://QmNftSDQawwTWbiuA9R1UDaorLZqBRBNRZ6PgkxuPznxij",
          "background": "Purple ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT053": {
          "name": "Lil Turt #053",
          "image": "ipfs://Qmd31KrAHxTwiafoa7ny6iP9Xa8PKNu9sXeFHfcBV9ugwv",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT054": {
          "name": "Lil Turt #054",
          "image": "ipfs://QmX2SYSeFApkYfpZ9F9P6HWW2T5pKWqjtAytVY5zPiQAD8",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Steel Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT055": {
          "name": "Lil Turt #055",
          "image": "ipfs://QmQ3epDepttFezrhFXZeNAJSnRHMXmXTrddh7CTDhWEeJN",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "White Hair ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT056": {
          "name": "Lil Turt #056",
          "image": "ipfs://QmRTd9VBGScDEFTe76aRj27eMRvj3tY1NjPDo6cs5DR6GL",
          "background": "Purple ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "White Hair ",
          "shell": "Base Shell ",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "Dark Angel Wings (super super rare)"
      },
        "TURT057": {
          "name": "Lil Turt #057",
          "image": "ipfs://QmRvCHxxRsWBe2Ap5AD2sjtPoJnzjzq8zH2W7ossMeJ8qM",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Steel Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "Staff Right (rare)",
          "wings": "none "
      },
        "TURT058": {
          "name": "Lil Turt #058",
          "image": "ipfs://QmV775WJA6p8ADeU43JG7vyWSN5Ut4Wo5h7pjg1PfCEXQa",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Steel Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT059": {
          "name": "Lil Turt #059",
          "image": "ipfs://QmRdakcR85SBrisdSfDksE4u5GuHLmUwP6ojmuP6HES7mT",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Winter Hat ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT060": {
          "name": "Lil Turt #060",
          "image": "ipfs://QmaSmvU7rmKaE3bJP7USMmHTWkVK3gFifrQQPfNTgV1Wgq",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "Angel Wings (super super rare)"
      },
        "TURT061": {
          "name": "Lil Turt #061",
          "image": "ipfs://QmR4NZ9v5JpuCtu5KwkNkcGbwWxVNvEKwDRSYhbFJHyVSv",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "none ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT062": {
          "name": "Lil Turt #062",
          "image": "ipfs://QmSDYr2qcg5zqM4pVJuW8fievKwCLgiDAdKyhyLJcdVKm3",
          "background": "Tan ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Flowers ",
          "weapons": "Staff Right (rare)",
          "wings": "none "
      },
        "TURT063": {
          "name": "Lil Turt #063",
          "image": "ipfs://QmbFx5HhjEZ2zsCLhYaL2Sm8VfnnGA6t8ko7E1gSksFFG6",
          "background": "Pink ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "Dark Angel Wings (super super rare)"
      },
        "TURT064": {
          "name": "Lil Turt #064",
          "image": "ipfs://QmQN9Ft61bPcU7ZQa4pppXa4jMcvvwrn9E6rQ9XHUcTCBz",
          "background": "Pink ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "Winter Hat ",
          "shell": "Steel Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT065": {
          "name": "Lil Turt #065",
          "image": "ipfs://QmaZwY3hDXJFcgKzCtpNog2cT9aEpjXXucWiH9gHnYJmcr",
          "background": "Purple ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Steel Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT066": {
          "name": "Lil Turt #066",
          "image": "ipfs://QmWokBU9GB7BKKtn9WuuKa19jyF37nSqsBBvhekWQdhxcE",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Steel Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT067": {
          "name": "Lil Turt #067",
          "image": "ipfs://QmVV7ckFWE9phwnBR5i9Rps2GV2Tg6AGkMX49ffwkrBXBN",
          "background": "Pink ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT068": {
          "name": "Lil Turt #068",
          "image": "ipfs://QmUdWzaPg7jYAuLqTH31RNY93GP8538keeW6wCMJRV177W",
          "background": "Blue ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "none ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "Angel Wings (super super rare)"
      },
        "TURT069": {
          "name": "Lil Turt #069",
          "image": "ipfs://QmRwBiu5j2sMsy6TLEMGAChDZHgDKgKBfszBY7Jvn1crX8",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Steel Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT070": {
          "name": "Lil Turt #070",
          "image": "ipfs://QmSSainqkaKGNkVcnT5ehorpLdbipFUyMboQ4iTvhmW639",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "Winter Hat ",
          "shell": "Base Shell ",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT071": {
          "name": "Lil Turt #071",
          "image": "ipfs://QmYxhXbzrFzJf8QbfjLjoGghSy6txdDhneahvJAdNvvdPZ",
          "background": "Pink ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT072": {
          "name": "Lil Turt #072",
          "image": "ipfs://QmbE2LtMvmJwVK34PVNcqJNbYcgR796KtFATrQPkkrwh3t",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Gold Shell (super rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT073": {
          "name": "Lil Turt #073",
          "image": "ipfs://QmbrGt34z4A21FaWvcpfE2zdYeFfafXn5RJANb7Huywczd",
          "background": "Pink ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "Staff Left (rare)",
          "wings": "Rainbow Wings (super super rare)"
      },
        "TURT074": {
          "name": "Lil Turt #074",
          "image": "ipfs://QmWTVneJUu7bi5bdzASQkCtia9FcVThf9QBRc3CGbh1bx7",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Base Shell ",
          "handheld": "Flowers ",
          "weapons": "Staff Right (rare)",
          "wings": "none "
      },
        "TURT075": {
          "name": "Lil Turt #075",
          "image": "ipfs://QmYDLWsBgDoVAracc19pcYWffAP5bGAvRP9fxv4AJZdfr7",
          "background": "Tan ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      }
    }
  }
}

//76-100

{
  "721": {
    "<policy>": {
        "TURT076": {
          "name": "Lil Turt #076",
          "image": "ipfs://QmUCVsqKepjB8NQXq94yetP5G5nKsqcDpc2UhjpTX2oSMZ",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Gold Shell (super rare)",
          "handheld": "Flowers ",
          "weapons": "Staff Left (rare)",
          "wings": "none "
      },
        "TURT077": {
          "name": "Lil Turt #077",
          "image": "ipfs://QmZrN4GC1jmMFFeerrLghfiBMMkmBVYJp3u9seatdoBhnm",
          "background": "Purple ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "Staff Right (rare)",
          "wings": "none "
      },
        "TURT078": {
          "name": "Lil Turt #078",
          "image": "ipfs://QmU5rNnViWxGj3ENWAL5VwtBr65gwqTEMTNaJtkgNzuigX",
          "background": "Purple ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "Winter Hat ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT079": {
          "name": "Lil Turt #079",
          "image": "ipfs://QmTqKiwNcwt9MwS9HZBGYFaa5L1i8ZJ8vXakLEWUw8DWmq",
          "background": "Purple ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT080": {
          "name": "Lil Turt #080",
          "image": "ipfs://QmRWXxnyqTq8Yo9CBjmJkeD8hppaaic32fsTw8XQEweo5p",
          "background": "Purple ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT081": {
          "name": "Lil Turt #081",
          "image": "ipfs://QmbiFMRbZSnFQDwWuJBg3kutcoryhtJvqFPxnKB8Zv92kN",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Steel Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT082": {
          "name": "Lil Turt #082",
          "image": "ipfs://QmYkLj6aT6gPipHFTjQzABRvotEJmnGkqYz9Gk6pfi5uGU",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT083": {
          "name": "Lil Turt #083",
          "image": "ipfs://QmbFQyHRXLyrjHNRcSB3rkmzPyhadRzCDh9jHbzV5aS9nw",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT084": {
          "name": "Lil Turt #084",
          "image": "ipfs://QmWY4KDWoC7gwEmhQnQj8tYSoYwGK1sRnHJNRUQ64dRQW9",
          "background": "Purple ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT085": {
          "name": "Lil Turt #085",
          "image": "ipfs://QmXJmKz7onCuHhJWTWvnA4b8iaDAZe1PP8nios17rgn3wx",
          "background": "Blue ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT086": {
          "name": "Lil Turt #086",
          "image": "ipfs://QmbiFMRbZSnFQDwWuJBg3kutcoryhtJvqFPxnKB8Zv92kN",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Steel Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT087": {
          "name": "Lil Turt #087",
          "image": "ipfs://QmeA4Xw3afvDtwRWFLVy2rkAqppjRfzc4Tp7QMcEMsJywg",
          "background": "Pink ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Winter Hat ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "Staff Left (rare)",
          "wings": "none "
      },
        "TURT088": {
          "name": "Lil Turt #088",
          "image": "ipfs://QmbxsF14ne6PpsAsLHvWU9CDgUJwXLVhtfJHguz9oxNfos",
          "background": "Pink ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT089": {
          "name": "Lil Turt #089",
          "image": "ipfs://QmXzDSuuLUVDdynyrqAA2uJMbT6Mv9HyHqQZXvCHCLBdfd",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "none ",
          "shell": "Steel Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "Dark Angel Wings (super super rare)"
      },
        "TURT090": {
          "name": "Lil Turt #090",
          "image": "ipfs://QmbKjCMYX5H2jTTvRpUfGqFamzL9LBsJ8oaisx11aiR3da",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "Staff Right (rare)",
          "wings": "none "
      },
        "TURT091": {
          "name": "Lil Turt #091",
          "image": "ipfs://QmTYwLRNocrLSjJs4NkpnfhDHVxBqrNyHGLvqhP8DDEmi2",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "none ",
          "shell": "Steel Shell (rare)",
          "handheld": "Sign ",
          "weapons": "Double Staff (rare)",
          "wings": "none "
      },
        "TURT092": {
          "name": "Lil Turt #092",
          "image": "ipfs://QmVzW8gxjGqaf75pAz4yxdpnmto4yWP5f9684QeNofdvE5",
          "background": "Purple ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT093": {
          "name": "Lil Turt #093",
          "image": "ipfs://QmZUt2Lw695sZVkpisWiyU89yruzsL6ux38AagV3qaC1LQ",
          "background": "Tan ",
          "skin": "Blue ",
          "eyes": "Blue ",
          "head": "Fire Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT094": {
          "name": "Lil Turt #094",
          "image": "ipfs://QmWL1sbh4TFYjbz13n9BULhRSnKorE4YR5TMz8eU3Amt7Z",
          "background": "Purple ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Flowers ",
          "weapons": "Staff Left (rare)",
          "wings": "none "
      },
        "TURT095": {
          "name": "Lil Turt #095",
          "image": "ipfs://QmX4UgD2CQ7euuT64ZKDUVF6YtFzWZfjxrF6vsryrzfzLb",
          "background": "Tan ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Sign ",
          "weapons": "Staff Right (rare)",
          "wings": "none "
      },
        "TURT096": {
          "name": "Lil Turt #096",
          "image": "ipfs://QmPxoiLREPS68nyfMwieoj5PgJsYbduuhoCBcamqpK6p83",
          "background": "Pink ",
          "skin": "Red ",
          "eyes": "Blue ",
          "head": "Graffiti King (rare)",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Ice Cream Cone ",
          "weapons": "none ",
          "wings": "Rainbow Wings (super super rare)"
      },
        "TURT097": {
          "name": "Lil Turt #097",
          "image": "ipfs://QmTMsSxN1sk3TPhreHtUxxkcL7farqGxDuKxMNLFw7yxym",
          "background": "Blue ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT098": {
          "name": "Lil Turt #098",
          "image": "ipfs://QmNn34k68tyfo7A5XF9TsYqzJAJVzA6BoHS12iGPoMUTfX",
          "background": "Blue ",
          "skin": "Red ",
          "eyes": "Black ",
          "head": "none ",
          "shell": "Steel Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT099": {
          "name": "Lil Turt #099",
          "image": "ipfs://QmXmg2GwnH5gdr35kVteGN1KsBrRRZYR7gNaCc2gyRuGRi",
          "background": "Blue ",
          "skin": "Green ",
          "eyes": "Blue ",
          "head": "White Hair ",
          "shell": "Rainbow Shell (rare)",
          "handheld": "Flowers ",
          "weapons": "none ",
          "wings": "none "
      },
        "TURT100": {
          "name": "Lil Turt #100",
          "image": "ipfs://Qmb55Q61jGayXK59nNcPowyEVvDvPA23W5Aqm1dDrZRJjf",
          "background": "Blue ",
          "skin": "Green ",
          "eyes": "Black ",
          "head": "Graffiti King (rare)",
          "shell": "Base Shell ",
          "handheld": "Sign ",
          "weapons": "none ",
          "wings": "Rainbow Wings (super super rare)"
      }
    }
  }
}